/*
 * Pharmacy Management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xmikova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_orders

import (
	"github.com/gin-gonic/gin"
)

type PharmacyMedicinesAPI interface {

	// GetMedicines Get /api/pharmacy/:pharmacyId/medicines
	// Provides the list of medicines in inventory
	GetMedicines(c *gin.Context)

	// CreateMedicine Post /api/pharmacy/:pharmacyId/medicines
	// Adds new medicine to inventory
	CreateMedicine(c *gin.Context)

	// GetMedicine Get /api/pharmacy/:pharmacyId/medicines/:medicineId
	// Provides details about specific medicine
	GetMedicine(c *gin.Context)

	// UpdateMedicine Put /api/pharmacy/:pharmacyId/medicines/:medicineId
	// Updates specific medicine
	UpdateMedicine(c *gin.Context)

	// DeleteMedicine Delete /api/pharmacy/:pharmacyId/medicines/:medicineId
	// Removes medicine from inventory
	DeleteMedicine(c *gin.Context)
}
