/*
 * Waiting List Api
 *
 * Pharmacy Management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xmikova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_orders
// OrderStatus : Status of the medication order
type OrderStatus string

// List of OrderStatus
const (
	CREATED OrderStatus = "created"
	CONFIRMED OrderStatus = "confirmed"
	DELIVERED OrderStatus = "delivered"
	CANCELLED OrderStatus = "cancelled"
)
