/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xmikova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"time"
)

type Order struct {

	// Unique identifier of the order
	Id string `json:"id"`

	// Identifier of the pharmacy placing the order
	PharmacyId string `json:"pharmacyId"`

	// Identifier of the supplier (optional)
	SupplierId string `json:"supplierId,omitempty"`

	// List of ordered medicines
	Items []OrderItem `json:"items"`

	Status OrderStatus `json:"status"`

	// Timestamp when order was created
	CreatedAt time.Time `json:"createdAt"`

	// Timestamp when order was last updated
	UpdatedAt time.Time `json:"updatedAt,omitempty"`

	// User ID who created the order
	CreatedBy string `json:"createdBy,omitempty"`

	// Additional notes for the order
	Notes string `json:"notes,omitempty"`
}
