/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xmikova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

type OrderItem struct {

	// Unique identifier of the medicine
	MedicineId string `json:"medicineId"`

	// Name of the medicine (for reference)
	MedicineName string `json:"medicineName,omitempty"`

	// Quantity to order
	Quantity int32 `json:"quantity"`

	// Unit of measurement (tablets, bottles, boxes, etc.)
	Unit string `json:"unit,omitempty"`

	// Price per unit
	UnitPrice float64 `json:"unitPrice"`

	// Total price for this item (quantity * unitPrice)
	TotalPrice float64 `json:"totalPrice,omitempty"`
}
